language: julia

os:
  - linux
  - osx

julia:
  - 0.5
  - nightly
  
notifications:
  email: false

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("BioSimulator")); include(joinpath("docs", "make.jl"))'
