language: julia

os:
  - linux

julia:
  - 0.5

notifications:
  email: false

after_success:
  - julia -e 'Pkg.add("Documenter"); Pkg.add("JSON")'
  - julia -e 'cd(Pkg.dir("BioSimulator")); include(joinpath("docs", "make.jl"))'
