language: julia

sudo: required

os:
  - linux

julia:
  - 0.5

notifications:
  email: false
  
before_install:
  - sudo apt-get install -y pdf2svg

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("BioSimulator")); include(joinpath("docs", "make.jl"))'
