language: julia
os: linux

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - nightly

jobs:
  allow_failures:
    - julia: 1.0
    - julia: 1.1
    - julia: nightly
  include:
  - stage: "Documentation"
    julia: 1.4
    os: linux
    script:
      - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
      - julia --project=docs --color=yes docs/make.jl
    after_success: skip

notifications:
  email: false

#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Example"); Pkg.test("Example"; coverage=true)';
