site_name:        BioSimulator.jl
repo_url:         https://bitbucket.com/alanderos/BioSimulator.jl
site_description: A stochastic simulation framework in Julia.
site_author:      alanderos

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
